microservice-chart:
  namespace: "idpay"
  nameOverride: ""
  fullnameOverride: ""

  livenessProbe:
    handlerType: httpGet
    httpGet:
      path: /actuator/health
      port: 8080
    initialDelaySeconds: 120
    failureThreshold: 15
    periodSeconds: 10

  readinessProbe:
    handlerType: httpGet
    httpGet:
      path: /actuator/health
      port: 8080
    initialDelaySeconds: 120
    failureThreshold: 15
    periodSeconds: 10

  deployment:
    create: true

  service:
    create: true
    type: ClusterIP
    ports:
      - 8080

  ingress:
    create: true
    path: /idpayiban/(.*)
    servicePort: 8080

  serviceAccount:
    create: false
    annotations: {}
    name: ""

  podAnnotations: {}

  podSecurityContext:
    seccompProfile:
      type: RuntimeDefault

  securityContext:
    allowPrivilegeEscalation: false
    runAsNonRoot: true
    runAsUser: 10000
    runAsGroup: 10000

  envConfig:
    MONGODB_DBNAME: idpay
    APPLICATIONINSIGHTS_ROLE_NAME: "idpayiban"
    APPLICATIONINSIGHTS_INSTRUMENTATION_LOGGING_LEVEL: "OFF"
    APPLICATIONINSIGHTS_INSTRUMENTATION_MICROMETER_ENABLED: "false"
    APPLICATIONINSIGHTS_PREVIEW_PROFILER_ENABLED: "false"
    CHECKIBAN_SERVICE_CODE: pagopa-checkiban
    PDV_DECRYPT_SERVICE_CODE: pdv-ms-tokenizer
    HEALTH_MONGO_ENABLED: "false"

  externalConfigMapValues:
    idpay-common:
      TZ: TZ
    rest-client:
      CHECKIBAN_BASE_URL: checkiban_base_url
      CHECKIBAN_URL: checkiban_url
      PDV_DECRYPT_BASE_URL: pdv_decrypt_base_url
    idpay-eventhub-00:
      KAFKA_BINDER_BROKER_ENDPOINT_LIST: kafka_broker
      KAFKA_IBAN_SASL_MECHANISM: kafka_sasl_mechanism
      KAFKA_IBAN_SECURITY_PROTOCOL: kafka_security_protocol
      KAFKA_TOPIC_WALLET: idpay_checkiban_outcome_topic
      KAFKA_TOPIC_IBAN: idpay_checkiban_evaluation_topic
      KAFKA_CHECKIBAN_CONSUMER_GROUP: idpay-checkiban-eval-consumer-group
    idpay-eventhub-01:
      KAFKA_BINDER_BROKER_ENDPOINT_ERRORS: kafka_broker
      KAFKA_TOPIC_ERRORS: idpay_error_topic

  envSecret:
    MONGODB_URI: mongodb-connection-string
    KAFKA_IBAN_SASL_JAAS_CONFIG: evh-idpay-checkiban-evaluation-idpay-checkiban-evaluation-consumer-jaas-config-idpay-00
    KAFKA_WALLET_SASL_JAAS_CONFIG: evh-idpay-checkiban-outcome-idpay-checkiban-outcome-producer-jaas-config-idpay-00
    CHECKIBAN_API_KEY: checkiban-api-key
    CHECKIBAN_AUTHSCHEMA: checkiban-auth-schema
    PDV_DECRYPT_API_KEY: pdv-api-key
    KAFKA_ERRORS_SASL_JAAS_CONFIG: evh-idpay-errors-idpay-errors-producer-jaas-config-idpay-01

  # nodeSelector: {}

  # tolerations: []

  # affinity: {}

  externalConfigMapFiles:
    create: true
    configMaps:
      - name: appinsights-config
        key: applicationinsights.json